// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 16.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Templates.Mvc
{
    using CodeGenerator.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ControllersTemplate : CodeGenerator.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 4 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
 
	string className = TableMeta.Name + "Controller";
	FilePath = TableMeta.NameSpace + ".WebApp/Controllers/" + className + ".cs";

            
            #line default
            #line hidden
            this.Write(@"using System;
using System.Net;
using Orion.Api;
using Orion.Api.Extensions;
using Orion.Api.Models;
using Orion.Mvc.Attributes;
using Orion.Mvc.Security;
using Orion.Mvc.Extensions;
using System.Collections.Generic;
using System.Web.Mvc;
using ");
            
            #line 18 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Service;\r\nusing ");
            
            #line 19 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain;\r\nusing ");
            
            #line 20 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Enums;\r\nusing ");
            
            #line 21 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".WebApp.Models;\r\n\r\n\r\nnamespace ");
            
            #line 24 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".WebApp.Controllers \r\n{\r\n\t/// <summary>");
            
            #line 26 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\t//TODO [ActAuthorize(ACT.");
            
            #line 27 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("View)]\r\n\tpublic class ");
            
            #line 28 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" : Controller \r\n\t{\r\n\t\tpublic IServiceContext Svc { get; set; }\r\n\r\n\r\n\r\n\t\tprivate ");
            
            #line 34 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain toDomain(");
            
            #line 34 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel vm)\r\n\t\t{\r\n\t\t\tif(vm == null) { return null; }\r\n\r\n\t\t\tvar domain =  new ");
            
            #line 38 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain\r\n\t\t\t{\r\n");
            
            #line 40 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
 foreach(var col in ActiveColumns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 41 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = vm.");
            
            #line 41 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 42 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 43 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
 foreach(var col in WithColumns("ModifyBy", "ModifiedBy")) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 44 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" =  this.UserId(),\r\n");
            
            #line 45 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t};\r\n\r\n\t\t\treturn domain;\r\n\t\t}\r\n\r\n\t\t//FIXME For Edit (Get) Use Or Remove\r\n\t\tpriv" +
                    "ate ");
            
            #line 52 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel toViewModel(");
            
            #line 52 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain)\r\n\t\t{\r\n\t\t\tif (domain == null) { return null; }\r\n\r\n\t\t\treturn new ");
            
            #line 56 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel\r\n\t\t\t{\r\n");
            
            #line 58 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 59 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = domain.");
            
            #line 59 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 60 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"			};
		}


		//private ActionResult forbidden()
		//{
		//	return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
		//}





		public ActionResult Index()
		{
			return RedirectToAction(nameof(List));
		}

			   		 


		//[SearchRemember(Ignore = new[] { ""export"" })]
		public ActionResult List(WhereParams<");
            
            #line 83 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam, PageParams<");
            
            #line 83 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> pageParams, bool export = false)\r\n\t\t{\r\n\t\t\tif (export) { pageParams.PageIn" +
                    "dex = 1; pageParams.PageSize = -1; }\r\n\r\n\t\t\tPagination<");
            
            #line 87 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> domainPage = Svc.");
            
            #line 87 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(".GetPagination(findParam, pageParams);\r\n\t\t\tViewBag.Pagination = domainPage;\r\n\r\n\t\t" +
                    "\tif (!export) { return View(); }\r\n\t\t\treturn this.ExcelView($\"");
            
            #line 91 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("-{DateTime.Now:yyyyMMddHHmmss}.xls\");\r\n\t\t}\r\n\r\n\r\n\r\n\t\t[HttpGet]\r\n\t\t[UseViewPage(\"Fo" +
                    "rm\")]\r\n\t\t//TODO [ActAuthorize(ACT.");
            
            #line 98 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Create)]\r\n\t\tpublic ActionResult Create()\r\n\t\t{\r\n\t\t\tvar vm = new ");
            
            #line 101 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel\r\n\t\t\t{\r\n\t\t\t\t//TODO\r\n\t\t\t};\r\n\r\n\t\t\treturn View(vm);\r\n\t\t}\r\n\r\n\r\n\r\n\r\n\t\t[HttpPo" +
                    "st]\r\n\t\t[UseViewPage(\"Form\")]\r\n\t\t//TODO [ActAuthorize(ACT.");
            
            #line 114 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Create)]\r\n\t\tpublic ActionResult Create(");
            
            #line 115 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel vm)\r\n\t\t{\r\n\t\t\tif (!ModelState.IsValid) { return View(vm); }\r\n\r\n\t\t\t");
            
            #line 119 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain = toDomain(vm);\r\n\r\n\t\t\t");
            
            #line 121 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 121 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(" = Svc.");
            
            #line 121 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(".Save(domain);\r\n\r\n\t\t\tthis.SetStatusSuccess(\"儲存成功!!\");\r\n\t\t\treturn RedirectToAction" +
                    "(nameof(Edit), new { ");
            
            #line 124 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(" });\r\n\t\t}\r\n\r\n\t\t \r\n\r\n\r\n\t\t\r\n\t\t[HttpGet]\r\n\t\t[UseViewPage(\"Form\")]\r\n\t\t//TODO [ActAuth" +
                    "orize(ACT.");
            
            #line 133 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Edit)]\r\n\t\tpublic ActionResult Edit(");
            
            #line 134 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 134 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\t");
            
            #line 136 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain = Svc.");
            
            #line 136 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(".GetById(");
            
            #line 136 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n\t\t\tvar vm =  new ");
            
            #line 138 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel\r\n\t\t\t{\r\n");
            
            #line 140 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 141 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = domain.");
            
            #line 141 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 142 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t};\r\n\r\n\t\t\treturn View(vm);\r\n\t\t}\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\t\t[HttpPost]\r\n\t\t[UseViewPage(\"Fo" +
                    "rm\")]\r\n\t\t//TODO [ActAuthorize(ACT.");
            
            #line 156 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Edit)]\r\n\t\tpublic ActionResult Edit(");
            
            #line 157 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel vm, string action = null)\r\n\t\t{\r\n\t\t\tif (\"delete\".EqualsIgnoreCase(action" +
                    "))\r\n\t\t\t{\r\n\t\t\t\t//if (!User.AnyAct(ACT.");
            
            #line 161 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Delete)) { throw new OrionException(\"權限不足!!\"); }\r\n\r\n\t\t\t\tSvc.");
            
            #line 163 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(".Delete(vm.");
            
            #line 163 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\tthis.SetStatusSuccess(\"刪除成功!!\");\r\n\t\t\t\treturn View();\r\n\t\t\t}\r\n\r\n\t\t\tif (!Mod" +
                    "elState.IsValid) { return View(vm); }\r\n\r\n\t\t\t");
            
            #line 170 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain = toDomain(vm);\r\n\r\n\t\t\t");
            
            #line 172 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 172 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(" = Svc.");
            
            #line 172 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(".Save(domain);\r\n\r\n\t\t\tthis.SetStatusSuccess(\"儲存成功!!\");\r\n\t\t\treturn RedirectToAction" +
                    "(nameof(Edit), new { ");
            
            #line 175 "..\CodeGenerator\Templates\Mvc\ControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(" });\r\n\t\t}\r\n\r\n\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
