// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 16.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Templates.Wcf
{
    using System.Linq;
    using CodeGenerator.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DaoTemplate : CodeGenerator.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 4 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 
	string className = TableMeta.Name + "Dao";
	FilePath = TableMeta.NameSpace + ".Dao/Impl/" + className + ".cs";

            
            #line default
            #line hidden
            this.Write("using Orion.Api;\r\nusing Orion.Api.Extensions;\r\nusing Orion.Api.Models" +
                    ";\r\nusing ");
            
            #line 11 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Dao.Database;\r\nusing ");
            
            #line 12 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain;\r\nusing ");
            
            #line 13 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Enums;\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\n\r\n" +
                    "\r\nnamespace ");
            
            #line 19 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Dao.Impl\r\n{\r\n\t/// <summary>");
            
            #line 21 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\tpublic class ");
            
            #line 22 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" : I");
            
            #line 22 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tprivate ");
            
            #line 24 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataContextName));
            
            #line default
            #line hidden
            this.Write(" _dc;\r\n\r\n\t\tpublic ");
            
            #line 26 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 26 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DataContextName));
            
            #line default
            #line hidden
            this.Write(" dc)\r\n\t\t{\r\n\t\t\t_dc = dc;\r\n\t\t}\r\n\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\t//public Dictionary<int, st" +
                    "ring> GetDic(string status = null)\r\n\t\t//{\r\n\t\t//\tIQueryable<");
            
            #line 35 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.TableName));
            
            #line default
            #line hidden
            this.Write("> query = _dc.");
            
            #line 35 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.TableName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t//\tquery = query.WhereHas(x => x.UseStatus == status);\r\n\r\n\t\t//\tvar items = q" +
                    "uery.ToDictionary(x => x.");
            
            #line 38 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(", x => x.");
            
            #line 38 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(@"Name);
		//	return items;
		//}


		//TODO 程式產生未完成
		//public Dictionary<string, string> GetStatusItems()
		//{
		//	var items = new Dictionary<string, string>
		//	{
		//		{ ""y"", ""開啟"" },
		//		{ ""n"", ""關閉"" },
		//	};
		//	return items;
		//}

		private ");
            
            #line 54 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain toDomain(_");
            
            #line 54 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(" data)\r\n\t\t{\r\n\t\t\tif(data == null) { return null; }\r\n\r\n\t\t\tvar domain = new ");
            
            #line 58 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain \r\n\t\t\t{\r\n");
            
            #line 60 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
	   if(col.IsEnum) 
	   { WriteLine("\t\t\t\t{0} = data.{0}.ToEnum<{0}>(),", col.Name); }
	   else
	   { WriteLine("\t\t\t\t{0} = data.{0},", col.Name); }
} 
            
            #line default
            #line hidden
            this.Write("\t\t\t};\t\t\t\r\n\r\n\t\t\treturn domain;\r\n\t\t}\r\n\r\n\r\n\t\tprivate Func<_");
            
            #line 72 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 72 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> prepareToDomain(IEnumerable<_");
            
            #line 72 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(@"> list)
		{
//            int[] roleIds = list.ToArray(x => x.RoleId);
//
//            Func<int, List<int>> getUserIds = _dc.AMS_UserRole
//                .WhereIn(x => x.RoleId, roleIds)
//                .OrderBy(x => x.UserId)
//                .PrepareList(x => x.RoleId, x => x.UserId);

			return data =>
			{
				if (data == null) { return null; }

				");
            
            #line 85 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain = toDomain(data);\r\n\t\t\t\t//domain.UserIds = getUserIds(data.RoleId);\r" +
                    "\n\t\t\t\treturn domain;\r\n\t\t\t};\r\n\t\t}\r\n\r\n\r\n\t\tprivate IQueryable<_");
            
            #line 92 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("> getQuery(WhereParams<");
            
            #line 92 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam = null)\r\n\t\t{\r\n\t\t\tIQueryable<_");
            
            #line 94 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("> query =\r\n\t\t\t\tfrom x in _dc.");
            
            #line 95 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.TableName));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\tselect new _");
            
            #line 96 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t{\r\n");
            
            #line 98 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 99 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = x.");
            
            #line 99 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 100 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t};\r\n\r\n\r\n\t\t\tif (findParam == null) { return query; }\r\n\r\n\t\t\tquery = query.Where" +
                    "Builder(findParam)\r\n");
            
            #line 107 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
	if(col.IsEnum) 
	{ WriteLine("\t\t\t\t.WhereBind(x => x.{0}.ToString(), y => y.{0})", col.Name); }
	else
	{ WriteLine("\t\t\t\t.WhereBind(x => x.{0}, y => y.{0})", col.Name); }
} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t.Build();\r\n\r\n\t\t\treturn query;\r\n\t\t}\r\n\r\n\r\n\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\tpublic Pagina" +
                    "tion<");
            
            #line 122 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> GetPagination(WhereParams<");
            
            #line 122 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam, PageParams<");
            
            #line 122 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> pageParams)\r\n\t\t{\r\n\t\t\tIQueryable<_");
            
            #line 124 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("> query = getQuery(findParam);\r\n\r\n\r\n\t\t\tif (pageParams == null) { pageParams = Pag" +
                    "eParams<");
            
            #line 127 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain>.Unlimited(); }\r\n\r\n\t\t\ttry\r\n\t\t\t{\r\n\t\t\t\tquery = query.AdvancedOrderBy(pagePar" +
                    "ams.OrderField);\r\n\t\t\t}\r\n\t\t\tcatch (Exception)\r\n\t\t\t{\r\n\t\t\t\tquery = query.OrderBy(x " +
                    "=> x.");
            
            #line 135 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t}\r\n\r\n\r\n\t\t\tvar result = query.AsPagination(pageParams.PageIndex, pageParams" +
                    ".PageSize);\r\n\r\n\t\t\tFunc<_");
            
            #line 141 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 141 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> toDomain = prepareToDomain(result.List);\r\n\t\t\treturn result.As(x => toDoma" +
                    "in(x));\r\n\t\t}\r\n\r\n\t\t\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\t//public List<");
            
            #line 148 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> GetList(WhereParams<");
            
            #line 148 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam = null)\r\n\t\t//{\r\n\t\t//    List<_");
            
            #line 150 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("> list = getQuery(findParam).ToList();\r\n\t\t//\r\n\t\t//    Func<_");
            
            #line 152 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 152 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> toDomain = prepareToDomain(list);\r\n\t\t//    return list.ToList(x => toDoma" +
                    "in(x));\r\n\t\t//}\r\n\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\tpublic ");
            
            #line 158 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain GetById(");
            
            #line 158 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 158 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n\t\t\t_");
            
            #line 160 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(" data = getQuery().FirstOrDefault(x => x.");
            
            #line 160 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 160 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\tif (data == null) { return null; }\r\n\r\n\t\t\tFunc<_");
            
            #line 163 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 163 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> toDomain = prepareToDomain(new[] { data });\r\n\t\t\t");
            
            #line 164 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain = toDomain(data);\r\n\r\n\t\t\treturn domain;\r\n\t\t}\r\n\r\n\r\n\r\n\t\t//TODO 程式產生未完成" +
                    "\r\n\t\tpublic int Save(");
            
            #line 172 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain)\r\n\t\t{\r\n\t\t\t");
            
            #line 174 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.TableName));
            
            #line default
            #line hidden
            this.Write(" data;\r\n\r\n\t\t\tif (domain.");
            
            #line 176 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(" > 0)\r\n\t\t\t{\r\n\t\t\t\tdata = _dc.");
            
            #line 178 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.TableName));
            
            #line default
            #line hidden
            this.Write(".FirstOrDefault(x => x.");
            
            #line 178 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(" == domain.");
            
            #line 178 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\tChecker.Has(data, \"");
            
            #line 179 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("不存在無法修改\");\r\n\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n\t\t\t\tdata = new ");
            
            #line 183 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.TableName));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t{\r\n");
            
            #line 185 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 foreach(var col in WithColumns("CreateBy")) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 186 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = domain.ModifyBy,\r\n");
            
            #line 187 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 188 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 foreach(var col in WithColumns("CreatedBy")) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 189 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = domain.ModifiedBy,\r\n");
            
            #line 190 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 191 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 foreach(var col in WithColumns("CreateDate", "CreatedDate")) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 192 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = DateTime.Now,\r\n");
            
            #line 193 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t};\r\n\t\t\t\t_dc.");
            
            #line 195 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.TableName));
            
            #line default
            #line hidden
            this.Write(".Add(data);\r\n\t\t\t}\r\n\r\n");
            
            #line 198 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 foreach(var col in ActiveColumns.Where(x => x.Name != TableMeta.PK.Name)) {
	   if(col.IsEnum) 
	   { WriteLine("\t\t\tdata.{0} = domain.{0}.ToString();", col.Name); }
	   else
	   { WriteLine("\t\t\tdata.{0} = domain.{0};", col.Name); }
} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 205 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 foreach(var col in WithColumns("ModifyBy", "ModifiedBy")) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tdata.");
            
            #line 206 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = domain.");
            
            #line 206 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 207 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 208 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 foreach(var col in WithColumns("ModifyDate", "ModifiedDate")) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tdata.");
            
            #line 209 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = DateTime.Now;\r\n");
            
            #line 210 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t_dc.SaveChanges();\r\n\r\n\r\n\t\t\treturn data.");
            
            #line 215 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t}\r\n\r\n\r\n\r\n\t\tpublic void Delete(");
            
            #line 220 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 220 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(", int modifyBy)\r\n\t\t{\r\n\t\t\t_dc.");
            
            #line 222 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.TableName));
            
            #line default
            #line hidden
            this.Write(".DeleteAllOnSubmit(x => x.");
            
            #line 222 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 222 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n\t\t\t_dc.SaveChanges();\r\n\t\t}\r\n\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\t//public bool IsXxxDupl" +
                    "icate(");
            
            #line 229 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 229 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(", string xxx)\r\n\t\t//{\r\n\t\t//\treturn _dc.");
            
            #line 231 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.TableName));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t//\t\t.Where(x => x. ");
            
            #line 232 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(" != ");
            
            #line 232 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t//\t\t.Where(x => x.Xxx == xxx)\r\n\t\t//\t\t.Any();\r\n\t\t//}\r\n\r\n\r\n\r\n\t\t/*#############" +
                    "#########################################################*/\r\n\r\n\t\tprivate class _" +
                    "");
            
            #line 241 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 241 "..\CodeGenerator\Templates\Wcf\DaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.TableName));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t}\r\n\r\n\t}\r\n\t\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
