<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- 專案會在建置後產生 NuGet 包 -->
    <TargetFramework>net8.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.1.2</Version>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <FileVersion>$(Version).0</FileVersion>
    <AssemblyName>OrionCore.Api</AssemblyName>
    <PackageId>OrionCore.Api</PackageId>
    <Authors>Jax Hu</Authors>
    <Company>Jax Hu</Company>
    <Product>OrionCore.Api</Product>
    <Description>Orion for ASP.NET Core</Description>
    <Copyright>Copyright © 2020 Jax Hu Information Co.</Copyright>
    <RootNamespace>Orion.Api</RootNamespace>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <PackageIcon>orion_logo.png</PackageIcon>    
    <IncludeSymbols>true</IncludeSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>$(MSBuildProjectDirectory)\OrionCore.Api.xml</DocumentationFile>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Extensions\NumberCommaExtensions.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="orion_logo.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Autofac" Version="5.1.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="4.7.12" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.24" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

 
  <Target Name="NugetPublish" AfterTargets="GenerateNuspec" Condition=" '$(Configuration)' == 'Release' ">
    <ItemGroup>
      <SymbolFiles Include="$(TargetDir)\..\*.symbols.nupkg" />
    </ItemGroup>    
    <Move SourceFiles="%(SymbolFiles.FullPath)" DestinationFiles="@(SymbolFiles -> Replace('.symbols.nupkg', '.nupkg'))" />

    <ItemGroup>
      <NupkgFiles Include="$(TargetDir)\..\*.nupkg" />
    </ItemGroup>
    <Move SourceFiles="%(NupkgFiles.FullPath)" DestinationFolder="bin\NugetArchive" OverwriteReadOnlyFiles="True" />

    <Message Text="##################################################################" />
  </Target>

</Project>
