<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- 專案會在建置後產生 NuGet 包 -->
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <AssemblyName>OrionCore.Mvc</AssemblyName>
    <PackageId>OrionCore.Mvc</PackageId>
    <Authors>Jax Hu</Authors>
    <Company>Jax Hu</Company>
    <Product>OrionCore.Mvc</Product>
    <Description>Orion for ASP.NET Core</Description>
    <Copyright>Copyright © 2020 Jax Hu Information Co.</Copyright>
    <RootNamespace>OrionCore.Mvc</RootNamespace>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>


  <ItemGroup>
    <Compile Remove="ModelBinder\DateTimeOffsetModelBinder.cs" />
  </ItemGroup>
  
  
  <ItemGroup>
    <None Remove="OCR-b.ttf" />
    <None Remove="UI\menus.xsd" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="OCR-b.ttf" />
    <EmbeddedResource Include="UI\menus.xsd" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrionCore.API\OrionCore.API.csproj" />
  </ItemGroup>

</Project>
